import { choiceArt } from './choice-art.js';
import { mountPalette } from './palette-ui.js';
import { playfulIcon } from './playful-icons.js';
import { BRUSHES, brushSegment } from './brushes.js';
import { makeCanvas } from './engine.js';

export function brushPreview(id,color,width=140,height=42,size=28){
  const canvas=makeCanvas(width*2,height*2),ctx=canvas.getContext('2d');ctx.scale(2,2);canvas.setAttribute('aria-hidden','true');
  const g={layer:{scale:1},options:{tool:'pen',brush:id,brushVersion:2,size,color,opacity:1,seed:913}};
  let a={x:18,y:height/2};brushSegment(ctx,g,a,a);for(let x=22;x<width-14;x+=4){const b={x,y:height/2+Math.sin((x-18)/(width-32)*Math.PI*2)*height*.13};brushSegment(ctx,g,a,b);a=b;}return canvas;
}

export function mountClassic({setTool,getColor,setColor,clearAnimations}){
  const el=id=>document.getElementById(id);document.body.classList.add('playroom');
  const workspace=document.querySelector('.workspace'),studio=document.querySelector('.studio');
  const left=document.createElement('aside');left.className='classic-left';left.setAttribute('aria-label','画笔盒');workspace.prepend(left);
  const heading=document.createElement('div');heading.className='canvas-topbar';const tabs=document.querySelector('.workspace-tabs');heading.append(tabs);const tip=document.createElement('span');tip.className='canvas-welcome';tip.textContent='每一笔，都是新发现';heading.append(tip);studio.prepend(heading);
  const parameter=document.createElement('section');parameter.className='classic-parameters';parameter.setAttribute('aria-label','当前工具参数');parameter.innerHTML='<div class="brush-inspector"><div id="active-brush-preview"></div><div><strong id="active-tool-name">铅笔</strong><span id="active-tool-description">细细的线，勾轮廓</span></div></div>';
  const options=document.querySelector('.options-bar');parameter.append(options);studio.append(parameter);
  const detailBar=document.querySelector('.detail-bar');
  const palette=document.querySelector('.palette');palette.className='quick-palette';parameter.before(palette);palette.querySelector('.palette-label').remove();palette.querySelector('.custom-color').hidden=true;
  const dock=document.createElement('section');dock.className='tool-dock';dock.setAttribute('aria-label','底部工具区');parameter.before(dock);dock.append(palette,parameter);
  const primary=document.createElement('div');primary.className='primary-brush-options';primary.setAttribute('aria-label','工具玩法与参数');primary.tabIndex=0;parameter.append(primary);if(detailBar)primary.append(detailBar);
  // The illustrated cards in the sidebar own these choices. Keep their source
  // controls connected for existing events, without duplicating them below.
  el('brush').dataset.directChoice='true';el('brush').hidden=true;
  for(const id of ['eraser-mode','fill-mode','selection-shape','selection-mode','geometry']){
    const control=el(id);control.dataset.directChoice='true';control.hidden=true;control.closest('label').classList.add('sidebar-choice-source');
  }
  el('background-color').closest('label').classList.add('sidebar-choice-source');
  const stroke=el('stroke-mode');stroke.dataset.directChoice='true';stroke.hidden=true;stroke.closest('label').classList.add('deprecated-stroke-control');stroke.closest('label').hidden=true;
  const modes=document.createElement('div');modes.id='stroke-buttons';modes.setAttribute('role','group');modes.setAttribute('aria-label','画笔方式');
  for(const option of stroke.options){const b=document.createElement('button');b.type='button';b.dataset.strokeMode=option.value;b.append(choiceArt(stroke,option),Object.assign(document.createElement('span'),{textContent:option.textContent}));b.onclick=()=>{stroke.value=option.value;stroke.dispatchEvent(new Event('change',{bubbles:true}));};modes.append(b);}
  const syncModes=()=>{for(const b of modes.children)b.setAttribute('aria-pressed',b.dataset.strokeMode===stroke.value);};stroke.addEventListener('change',syncModes);syncModes();options.append(el('brush-ratio').closest('label'));
  for(const control of [el('brush-options'),document.querySelector('.opacity-control'),el('brush-ratio').closest('label')])control.classList.add('parameter-slider');
  el('brush-ratio').type='range';el('brush-ratio').setAttribute('aria-label','笔尖宽窄');
  const ratioValue=document.createElement('output');ratioValue.id='ratio-value';el('brush-ratio').after(ratioValue);
  const showRatio=()=>{ratioValue.textContent=Number(el('brush-ratio').value).toFixed(2);};el('brush-ratio').addEventListener('input',showRatio);showRatio();parameter.append(primary);
  const moreColor=document.createElement('button');moreColor.className='more-colors';moreColor.innerHTML=playfulIcon('palette')+'<span>更多颜色</span>';moreColor.onclick=()=>el('palette-open').click();palette.append(moreColor);
  const status=document.querySelector('.canvas-footer');studio.append(status);const zoom=document.querySelector('.zoom-controls');heading.append(zoom);
  document.querySelector('.canvas-heading').hidden=true;
  const footer=document.createElement('div');footer.className='left-actions';
  const pens=document.createElement('div');pens.className='brush-box';pens.setAttribute('aria-label','九种画笔');const title=document.createElement('h2');title.textContent='我的画笔盒';left.append(title,pens);const libraryGroups=document.createElement('div');libraryGroups.id='library-groups';libraryGroups.setAttribute('aria-label','素材分类');left.append(libraryGroups);
  let currentBrush=el('brush').value;const sizes={};
  function chooseBrush(value){el('painting').dataset.brush=value;document.dispatchEvent(new Event('brushchange'));if(el('painting').dataset.tool==='pen')sizes[currentBrush]=Number(el('size').value);openLibrary(false);currentBrush=value;el('brush').value=value;el('size').value=sizes[value]||BRUSHES.find(b=>b.id===value).size;el('size').dispatchEvent(new Event('input',{bubbles:true}));setTool('pen');sync();document.dispatchEvent(new Event('controlschange'));}
  for(const brush of BRUSHES){const b=document.createElement('button');b.type='button';b.className='brush-card';b.dataset.brush=brush.id;b.style.setProperty('--brush-color',brush.color);b.setAttribute('aria-label',brush.name);b.title=brush.name+'：'+brush.hint;b.innerHTML=playfulIcon(brush.id)+`<span>${brush.name}</span><span class="brush-sample"></span>`;b.onclick=()=>{if(!document.body.hasAttribute('aria-busy'))chooseBrush(brush.id);};pens.append(b);const option=[...el('brush').options].find(o=>o.value===brush.id);option.textContent=brush.name;}
  pens.tabIndex=0;
  el('size').value=BRUSHES[0].size;el('size-value').textContent=BRUSHES[0].size;
  const subtools=document.createElement('div');subtools.className='subtool-box';left.append(subtools,modes,footer);
  const tools=[['pen','画笔'],['eraser','橡皮'],['stamp','魔法袋'],['fill','油漆桶'],['picker','吸颜色'],['line','图形'],['text','文字'],['select','圈选'],['magic','魔力棒'],['move','移动'],['warp','变形'],['board-filter','滤镜'],['clone','仿制印章'],['fractal','分形']];
  const geometries=['line','triangle','rect','pentagon','hexagon','roundrect','ellipse','star','polygon','bezier'];
  const groupTool=()=>geometries.includes(el('painting').dataset.tool)?'line':el('painting').dataset.tool;
  const bar=el('tools');bar.replaceChildren();let page=0;
  const flip=document.createElement('button');flip.id='tool-page';flip.className='tool-page';flip.setAttribute('aria-label','工具翻页');flip.onclick=()=>{page=1-page;renderTools();sync();};
  function renderTools(){bar.replaceChildren();for(const [id,name] of tools.slice(page*7,page*7+7)){const b=document.createElement('button');b.className='tool-button';b.dataset.tool=id;b.setAttribute('aria-label',name);b.innerHTML=playfulIcon(id==='pen'?'pencil':id)+`<span>${name}</span>`;b.onclick=()=>{if(document.body.hasAttribute('aria-busy'))return;setTool(id);if(id!=='stamp')openLibrary(false);if(id==='stamp'){document.querySelector('[data-category="fairy"]').click();openLibrary(true);}};bar.append(b);}flip.innerHTML=page?'<span>← 常用工具</span><small>2 / 2</small>':'<span>更多工具 →</span><small>1 / 2</small>';bar.after(flip);}
  renderTools();
  let lastColor='';
  function sync(){const tool=el('painting').dataset.tool,brush=BRUSHES.find(b=>b.id===el('brush').value);title.textContent=document.body.classList.contains('library-open')&&libraryGroups.children.length?'找一找图案':tool==='pen'?'我的画笔盒':(tools.find(t=>t[0]===groupTool())?.[1]||'工具')+'怎么玩';pens.hidden=tool!=='pen';subtools.replaceChildren();
    for(const b of pens.children)b.setAttribute('aria-pressed',b.dataset.brush===brush.id);el('painting').dataset.brush=brush.id;for(const b of bar.children)b.setAttribute('aria-pressed',b.dataset.tool===groupTool());
    if(getColor()!==lastColor){lastColor=getColor();for(const b of pens.children)b.querySelector('.brush-sample').replaceChildren(brushPreview(b.dataset.brush,lastColor,140,34,24));}
    const name=tool==='pen'?brush.name:tools.find(t=>t[0]===groupTool())?.[1]||'画画';el('active-tool-name').textContent=name;el('active-tool-description').textContent=tool==='pen'?brush.hint:'选好玩法，再到画纸上试一试';el('active-brush-preview').replaceChildren(tool==='pen'?brushPreview(brush.id,getColor(),140,50,Math.min(36,Number(el('size').value))):Object.assign(document.createElement('span'),{innerHTML:playfulIcon(groupTool())}));
    primary.hidden=false;modes.hidden=tool!=='pen';
    el('brush-options').hidden=!['pen','eraser','stamp','clone',...geometries].includes(tool)||(tool==='eraser'&&el('eraser-mode').value==='rect');document.querySelector('.opacity-control').hidden=['select','magic','move','warp','board-filter','picker','fractal'].includes(tool)||(tool==='eraser'&&el('eraser-mode').value==='rect');
    options.hidden=![...options.querySelectorAll('.parameter-slider')].some(item=>!item.hidden);
    document.querySelector('label[for="size"]').textContent=tool==='stamp'?'图案大小':'笔尖粗细';
    const map={eraser:'eraser-mode',fill:'fill-mode',select:'selection-shape',warp:'warp-kind','board-filter':'board-filter-kind'};const config=geometries.includes(tool)?'geometry':map[tool],select=config&&el(config);
    if(select){for(const option of select.options){const b=document.createElement('button');b.type='button';b.className='subtool-card';const label=document.createElement('span');label.textContent=option.textContent;b.append(choiceArt(select,option),label);b.setAttribute('aria-pressed',select.value===option.value);b.onclick=()=>{select.value=option.value;select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));sync();};subtools.append(b);}}
    else if(tool!=='pen'){const p=document.createElement('p');p.className='tool-coach';p.textContent=tool==='stamp'?'选好图案，调一调大小\n按住鼠标，连续画':el('tool-hint').textContent;subtools.append(p);if(tool==='stamp'){const edit=document.createElement('button');edit.className='subtool-card';edit.innerHTML=playfulIcon('move')+'<span>调整画里的图案</span>';edit.onclick=()=>{setTool('move');openLibrary(false);};subtools.append(edit);const modes=document.createElement('div');modes.className='fairy-modes';edit.before(modes);for(const [mode,label] of [['single','单张图案'],['static','组合图案'],['dynamic','会动图案']]){const b=document.createElement('button');b.className='subtool-card';b.innerHTML=playfulIcon(mode==='dynamic'?'effect':'stamp')+'<span>'+label+'</span>';b.setAttribute('aria-pressed',(document.body.dataset.fairyMode||'single')===mode);b.onclick=()=>{document.body.dataset.fairyMode=mode;document.dispatchEvent(new Event('fairymodechange'));openLibrary(true);sync();};modes.append(b);}}if(tool==='text'||tool==='fractal'){const b=document.createElement('button');b.className='primary';b.innerHTML=playfulIcon(tool)+'<span>'+(tool==='text'?'写几个字':'生成分形')+'</span>';b.onclick=()=>{if(tool==='fractal')el('fractal-open').click();else [...document.querySelectorAll('.detail-bar button')].find(n=>n.dataset.option==='text')?.click();};subtools.append(b);}}
    if(tool==='eraser'){const clear=document.createElement('button');clear.id='clear-animations';clear.className='subtool-card';clear.innerHTML=playfulIcon('eraser')+'<span>清除所有动图</span>';clear.title='保留背景和画笔；可以撤销';clear.onclick=clearAnimations;subtools.append(clear);}
  }
  document.addEventListener('toolchange',()=>{const i=tools.findIndex(t=>t[0]===groupTool());if(i>=0&&Math.floor(i/7)!==page){page=Math.floor(i/7);renderTools();}sync();});document.addEventListener('palettechange',sync);document.addEventListener('change',e=>{if(e.target===el('brush'))chooseBrush(e.target.value);else if(['geometry','eraser-mode','fill-mode','selection-shape','warp-kind','board-filter-kind'].includes(e.target.id))sync();});el('size').addEventListener('input',sync);
  function openLibrary(open){document.body.classList.toggle('library-open',open);el('mode-library').setAttribute('aria-pressed',open);el('mode-board').setAttribute('aria-pressed',!open);}
  new MutationObserver(()=>{const open=document.body.classList.contains('library-open');el('mode-library').setAttribute('aria-pressed',open);el('mode-board').setAttribute('aria-pressed',!open);if(open&&libraryGroups.children.length)title.textContent=document.body.dataset.librarySurface==='fairy'?'我的魔法袋':'找一找图案';else if(!open)sync();}).observe(document.body,{attributes:true,attributeFilter:['class']});
  el('mode-library').onclick=()=>{const opening=!document.body.classList.contains('library-open')||document.body.dataset.librarySurface==='fairy';if(opening)document.dispatchEvent(new Event('opengallery'));openLibrary(opening);};el('mode-board').addEventListener('click',()=>openLibrary(false));
  for(const [id,icon,label] of [['mode-board','paper','画板'],['darkroom','board-filter','暗房'],['mode-library','forest','图库']])el(id).innerHTML=playfulIcon(icon)+'<span>'+label+'</span>';
  const library=document.querySelector('.right-panel');dock.prepend(library);document.querySelector('.panel-heading h2').textContent='灵感百宝箱';
  const layer=el('layer-menu');layer.innerHTML=playfulIcon('layers')+'<span>我的图层</span>';footer.append(layer);const newPaper=el('new');newPaper.innerHTML=playfulIcon('new-paper')+'<span>新画纸</span>';footer.append(newPaper);
  const more=document.createElement('dialog');more.id='more-dialog';more.className='wide-dialog';more.innerHTML='<h2>创作工具箱</h2><div class="more-actions"></div><div class="dialog-actions"><button id="more-done">返回画纸</button></div>';document.body.append(more);const actions=more.querySelector('.more-actions');const paperSize=document.createElement('button');paperSize.id='paper-size-open';paperSize.type='button';paperSize.innerHTML=playfulIcon('paper')+'<span>画纸尺寸</span>';actions.append(paperSize);for(const id of ['copy','cut','paste','selection-menu','recordings','import-image'])actions.append(el(id));const aboutButton=document.createElement('button');aboutButton.id='about-open';aboutButton.type='button';aboutButton.innerHTML=playfulIcon('palette')+'<span>关于</span>';actions.append(aboutButton);actions.addEventListener('click',()=>more.close(),true);el('more-done').onclick=()=>more.close();const about=document.createElement('dialog');about.id='about-dialog';about.className='about-dialog';about.innerHTML='<div class="about-mark" aria-hidden="true"><img src="branding/app-icon.png" alt="落叶画板应用图标"></div><h2>落叶画板</h2><p class="about-version">版本 <strong id="about-version">开发版</strong></p><p class="about-credit">Power by ZX</p><p class="about-credit">For WenHe</p><div class="dialog-actions"><button id="about-close" class="primary">返回画纸</button></div>';document.body.append(about);if(window.LUOYE_PLATFORM==='windows')about.querySelector('.about-mark img').src='branding/app-icon-windows.png';about.querySelector('#about-version').textContent=window.LUOYE_VERSION||'开发版';aboutButton.onclick=()=>about.showModal();about.querySelector('#about-close').onclick=()=>about.close();
  const titleDialog=document.createElement('dialog');titleDialog.id='title-dialog';titleDialog.innerHTML='<h2>给画起个名字</h2><div class="dialog-actions"><button id="title-done" class="primary">就叫这个</button></div>';titleDialog.querySelector('h2').after(document.querySelector('.document-name'));document.body.append(titleDialog);const rename=document.createElement('button');rename.textContent='给画起名字';rename.onclick=()=>titleDialog.showModal();actions.append(rename);el('title-done').onclick=()=>titleDialog.close();
  const header=document.querySelector('.header-actions');header.prepend(el('new-quick'),el('undo'),el('redo'));for(const [id,icon,name] of [['undo','undo','撤销'],['redo','redo','重做'],['new-quick','new-paper','新画纸'],['reset-settings','reset-settings','重置'],['open','folder','打开'],['save','save','保存'],['export','download','导出'],['gallery','folder','画夹']]){el(id).innerHTML=playfulIcon(icon)+`<span>${name}</span>`;el(id).className='header-command';}
  const moreButton=document.createElement('button');moreButton.id='more-open';moreButton.className='header-command';moreButton.innerHTML=playfulIcon('more')+'<span>工具箱</span>';moreButton.onclick=()=>more.showModal();header.append(moreButton);
  document.querySelector('.brand').innerHTML=playfulIcon('palette')+'<span><strong>落叶画板</strong><small>我的暖暖画室</small></span>';
  const layerDialog=el('layer-dialog');layerDialog.querySelector('h2').textContent='我的图层';
  const help=document.createElement('p');help.className='layer-guide';help.textContent='每张小卡片都是画里的一部分。先点卡片，再移动或调整它。上面的会挡住下面的，背景一直在最下面。';
  layerDialog.querySelector('h2').after(help,document.querySelector('.layers-panel'));
  const advanced=document.createElement('details');advanced.className='layer-advanced';advanced.innerHTML='<summary>翻转、清空与更多操作</summary>';advanced.append(layerDialog.querySelector('.dialog-grid'),el('layer-opacity').closest('label'));layerDialog.querySelector('.dialog-actions').before(advanced);
  const layerActions=document.querySelector('.layer-actions');
  for(const [id,label,picture] of [['layer-up','往前一层','layers'],['layer-down','往后一层','layers'],['duplicate-layer','复制一份','copy'],['delete-layer','移走它','eraser']]){const b=el(id);b.innerHTML=playfulIcon(picture)+'<span>'+label+'</span>';b.setAttribute('aria-label',label);layerActions.append(b);}
  advanced.querySelector('.dialog-grid').prepend(el('rotate'));for(const [id,label,picture] of [['mirror-x','水平镜像','mirror-x'],['mirror-y','垂直镜像','mirror-y'],['smaller','变小','move'],['bigger','变大','move']]){el(id).innerHTML=playfulIcon(picture)+'<span>'+label+'</span>';layerActions.append(el(id));}
  const moveSelected=document.createElement('button');moveSelected.id='move-selected-layer';moveSelected.innerHTML=playfulIcon('move')+'<span>移动</span>';moveSelected.onclick=()=>{setTool('move');layerDialog.close();};layerActions.prepend(moveSelected);
  el('add-layer').innerHTML=playfulIcon('paper')+'<span>加一张透明画纸</span>';el('add-layer').setAttribute('aria-label','加一张透明画纸');
  layerDialog.querySelector('[data-close]').textContent='选好了，返回画纸';
  mountPalette({getColor,setColor});sync();return {groups:tools,sync};
}
