import { makeCanvas, loadImage } from './engine.js';
import { generateFractal } from './fractals.js';
import { warpPixels } from './warps.js';

export function mountCreative({engine,run,toast,getColor,setTool}) {
  const el=id=>document.getElementById(id),detail=document.querySelector('.detail-bar');
  const extra=document.createElement('div');extra.className='creative-options';extra.innerHTML=`
    <label data-option="warp">变形 <select id="warp-kind"><option value="push">推拉变形</option><option value="zoom">缩放变形</option></select></label><label data-option="warp">速度 <input id="warp-speed" type="range" min="-100" max="100" value="50"></label>
    <label data-option="warp board-filter">半径 <input id="creative-radius" type="range" min="10" max="600" value="120"></label>
    <label data-option="board-filter">滤镜 <select id="board-filter-kind"><option value="ripple">水纹滤镜</option><option value="twist">扭曲滤镜</option><option value="waterfall">瀑布滤镜</option><option value="point-light">点光源滤镜</option><option value="direction-light">方向光源滤镜</option></select></label>
    <label data-option="board-filter" data-filter="twist">曲度 <input id="filter-curvature" type="range" min="-360" max="360" value="120"></label><label data-option="board-filter" data-filter="waterfall point-light direction-light">密度 <input id="filter-density" type="range" min="0" max="100" value="50"></label>
    <label data-option="board-filter" data-filter="waterfall">扩展度 <input id="filter-spread" type="range" min="0" max="100" value="30"></label><label data-option="board-filter" data-filter="waterfall">高度 <input id="filter-height" type="range" min="0" max="100" value="50"></label><label data-option="board-filter" data-filter="waterfall">方向 <select id="filter-direction"><option value="right">向右</option><option value="left">向左</option></select></label>
    <label data-option="board-filter" data-filter="direction-light">角度 <input id="filter-angle" type="range" min="0" max="360" value="45"></label><button id="filter-preview-button" data-option="board-filter">预览／确定</button><button id="fractal-open" data-option="fractal">分形样式与参数</button>`;
  detail.append(extra);for(const input of extra.querySelectorAll('input[type=range]')){const output=document.createElement('output');output.textContent=input.value;input.after(output);input.oninput=()=>output.textContent=input.value;}
  function options(){return {warpKind:el('warp-kind').value,speed:Number(el('warp-speed').value),radius:Number(el('creative-radius').value),filterKind:el('board-filter-kind').value,curvature:Number(el('filter-curvature').value),density:Number(el('filter-density').value),spread:Number(el('filter-spread').value),height:Number(el('filter-height').value),direction:el('filter-direction').value,angle:Number(el('filter-angle').value)};}
  function showOptions(){const tool=el('painting').dataset.tool;for(const item of extra.querySelectorAll('[data-option]'))item.hidden=!item.dataset.option.split(' ').includes(tool)||(item.dataset.filter&&!item.dataset.filter.split(' ').includes(el('board-filter-kind').value));}
  document.addEventListener('toolchange',showOptions);el('board-filter-kind').onchange=showOptions;showOptions();
  const filterDialog=document.createElement('dialog');filterDialog.className='wide-dialog';filterDialog.innerHTML='<h2>画板滤镜</h2><div class="effect-preview" id="board-preview"></div><p>预览以画纸中心为作用点；也可关闭后点击画纸指定位置。小伙伴会继续播放动画。</p><div class="dialog-actions"><button id="board-cancel">取消</button><button id="board-apply" class="primary">确定</button></div>';document.body.append(filterDialog);
  el('filter-preview-button').onclick=()=>run(()=>{
    const width=engine.paperMode?engine.width:engine.active.width,height=engine.paperMode?engine.height:engine.active.height,scale=Math.min(1,400/Math.max(width,height));
    const original=makeCanvas(width,height);if(engine.paperMode)engine.paint(original.getContext('2d'));else engine.drawLayer(original.getContext('2d'),engine.active);
    const c=makeCanvas(Math.max(1,Math.round(width*scale)),Math.max(1,Math.round(height*scale))),ctx=c.getContext('2d');ctx.drawImage(original,0,0,c.width,c.height);
    const data=ctx.getImageData(0,0,c.width,c.height);data.data.set(warpPixels(data.data,c.width,c.height,{...options(),kind:options().filterKind,radius:options().radius/(engine.paperMode?1:engine.active.scale)*scale}));ctx.putImageData(data,0,0);el('board-preview').replaceChildren(c);filterDialog.showModal();
  });
  el('board-cancel').onclick=()=>filterDialog.close();el('board-apply').onclick=()=>run(async()=>{filterDialog.close();el('tool-settings')?.close();await engine.applyBoardFilter(options().filterKind,{...options(),radius:options().radius/(engine.paperMode?1:engine.active.scale)});});
  const dialog=document.createElement('dialog');dialog.id='fractal-dialog';dialog.className='wide-dialog';dialog.innerHTML=`<h2>分形</h2><div class="effect-layout"><div><label>分形类别 <select id="fractal-kind"><option value="ifs">分形 1 · IFS 集</option><option value="mandel">分形 2 · Mandel 集</option><option value="julia">分形 3 · Julia 集</option><option value="norton">分形 4 · Norton 原版样式</option></select></label><div class="fractal-style"><button id="fractal-prev" aria-label="上一个分形样式">◀</button><button id="fractal-style" title="左键换样式，右键复位">样式 1</button><button id="fractal-next" aria-label="下一个分形样式">▶</button></div><label>宽度 <input id="fractal-width" type="number" min="16" max="2560" value="640"></label><label>高度 <input id="fractal-height" type="number" min="16" max="2560" value="480"></label><div id="fractal-density-row"><label>密度 <input id="fractal-density" type="range" min="1" max="100" value="50"></label></div><div id="fractal-bounds">${[['left','左',-2.3],['right','右',1],['top','上',-1.3],['bottom','下',1.3]].map(([key,name,value])=>`<label>${name} <input id="fractal-${key}" type="number" min="-10" max="10" step="0.01" value="${value}"></label>`).join('')}</div><button id="fractal-refresh">更新预览</button></div><div class="effect-preview"><div id="fractal-preview"></div><output id="fractal-progress" role="status"></output><p id="fractal-note"></p></div></div><div class="dialog-actions"><button id="fractal-cancel">取消</button><button id="fractal-add" class="primary">放入画纸</button></div>`;document.body.append(dialog);
  let preset=0,controller=null,rendering=false;
  const counts={ifs:3,mandel:4,julia:4,norton:20};
  function fractalOptions(preview=false){const kind=el('fractal-kind').value,w=Number(el('fractal-width').value),h=Number(el('fractal-height').value);if(!Number.isInteger(w)||!Number.isInteger(h)||w<16||h<16||w>2560||h>2560||w*h>4000000)throw new Error('分形尺寸需为 16～2560，且不超过 4 百万像素。');const scale=preview?Math.min(1,320/Math.max(w,h)):1;return {kind,preset,width:Math.max(16,Math.round(w*scale)),height:Math.max(16,Math.round(h*scale)),density:Number(el('fractal-density').value),color:getColor(),...Object.fromEntries(['left','right','top','bottom'].map(key=>[key,Number(el('fractal-'+key).value)]))};}
  async function generate(preview){controller?.abort();const own=new AbortController();controller=own;const o=fractalOptions(preview);let c;if(o.kind==='norton'){const image=await loadImage('classic/paint/fr_kind3.jpg');if(own.signal.aborted)throw new DOMException('取消','AbortError');c=makeCanvas(o.width,o.height);c.getContext('2d').drawImage(image,(preset%20)*60,0,60,40,0,0,c.width,c.height);}else{const pixels=await generateFractal(o,{signal:own.signal,onProgress:p=>{if(controller===own)el('fractal-progress').textContent=Math.round(p*100)+'%';}});c=makeCanvas(pixels.width,pixels.height);c.getContext('2d').putImageData(new ImageData(pixels.data,pixels.width,pixels.height),0,0);}return c;}
  async function preview(){try{el('fractal-preview').replaceChildren(await generate(true));}catch(e){if(e.name!=='AbortError')el('fractal-progress').textContent=e.message;}}
  function selected(){const kind=el('fractal-kind').value;preset%=counts[kind];el('fractal-style').textContent='样式 '+(preset+1)+' / '+counts[kind];el('fractal-density-row').hidden=kind!=='ifs';el('fractal-bounds').hidden=!['mandel','julia'].includes(kind);el('fractal-note').textContent=kind==='norton'?'原版 60×40 样式预览素材，放大会模糊；高清分形计算仍待核实。':'';preview();}
  function step(delta){if(rendering)return;preset=(preset+delta+counts[el('fractal-kind').value])%counts[el('fractal-kind').value];selected();}
  el('fractal-prev').onclick=()=>step(-1);el('fractal-next').onclick=el('fractal-style').onclick=()=>step(1);el('fractal-style').oncontextmenu=e=>{e.preventDefault();if(rendering)return;preset=0;selected();};el('fractal-kind').onchange=()=>{preset=0;const julia=el('fractal-kind').value==='julia';el('fractal-left').value=julia?-1.8:-2.3;el('fractal-right').value=julia?1.8:1;selected();};el('fractal-refresh').onclick=preview;
  function open(){if(rendering)return;selected();dialog.showModal();}el('fractal-open').onclick=open;
  function cancel(){controller?.abort();dialog.close();}el('fractal-cancel').onclick=cancel;dialog.addEventListener('cancel',cancel);
  el('fractal-add').onclick=()=>run(async()=>{rendering=true;for(const control of dialog.querySelectorAll('input,select,button'))if(control.id!=='fractal-cancel')control.disabled=true;try{const c=await generate(false);engine.addLayer('分形 · '+el('fractal-kind').selectedOptions[0].textContent,c);dialog.close();setTool('move');}catch(e){if(e.name!=='AbortError')throw e;}finally{rendering=false;for(const control of dialog.querySelectorAll('input,select,button'))control.disabled=false;}});
  return {options,open};
}
