import { playfulIcon } from './playful-icons.js';
export function mountMusic({run,toast}) {
  const tracks=window.LUOYE_MUSIC_TRACKS;
  const el=id=>document.getElementById(id),button=document.createElement('button');button.id='music-open';button.className='header-command';button.innerHTML=playfulIcon('music')+'<span>音乐</span>';button.title='音乐盒';document.querySelector('.header-actions').append(button);
  const dialog=document.createElement('dialog');dialog.id='music-dialog';dialog.className='music-dialog';dialog.innerHTML=`<h2>音乐盒</h2><label for="music-track">背景音乐</label><div class="music-tracks"><button id="music-prev" aria-label="上一首">◀</button><select id="music-track">${tracks.map((_,i)=>`<option value="${i}">音乐${i+1}</option>`).join('')}</select><button id="music-next" aria-label="下一首">▶</button></div><p id="music-state" role="status">点击播放，边听边画。每首音乐会重复播放。</p><div class="music-transport"><button id="music-play">▶ 播放</button><button id="music-stop">■ 停止</button></div><label>音量 <input id="music-volume" type="range" min="0" max="100" value="50"><output id="music-volume-value">50%</output></label><label class="sound-toggle"><input id="ui-sounds" type="checkbox" checked> 工具切换音效</label><button id="music-import">输入 MIDI 音乐</button><input id="music-file" type="file" accept=".mid,.midi,audio/midi" hidden><div class="dialog-actions"><button id="music-close" class="primary">确定</button></div>`;document.body.append(dialog);
  const pending=new Map(),soundToggle=dialog.querySelector('#ui-sounds'),bridge=window.webkit?.messageHandlers?.music;let loaded=false,poll=null;
  function request(action,args={}){if(!bridge)return Promise.reject(new Error('请在桌面客户端中播放音乐。'));const id=crypto.randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('音乐播放器没有响应，请重试。'));},20000);pending.set(id,{resolve,reject,timer});bridge.postMessage({id,action,...args});});}
  function state(value){if(!value)return;const format=n=>Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0');el('music-state').textContent=`${value.name} · ${value.playing?'单曲循环中':'已停止'} ${format(value.position)} / ${format(value.duration)}`;el('music-volume').value=Math.round(value.volume*100);el('music-volume-value').textContent=Math.round(value.volume*100)+'%';button.setAttribute('aria-label',value.playing?'音乐：播放中':'音乐：已停止');button.dataset.playing=String(value.playing);}
  window.addEventListener('native-music-result',event=>{const r=event.detail,p= pending.get(r.id);if(!p)return;clearTimeout(p.timer);pending.delete(r.id);if(r.error)p.reject(new Error(r.error));else{state(r.state);p.resolve(r.state);}});
  const track=async()=>{await request('track',{index:Number(el('music-track').value)});loaded=true;};
  try{soundToggle.checked=localStorage.getItem('luoye-ui-sounds')!=='off';}catch{} soundToggle.onchange=()=>{try{localStorage.setItem('luoye-ui-sounds',soundToggle.checked?'on':'off');}catch{};document.dispatchEvent(new Event('soundsettingchange'));};
  button.onclick=()=>{dialog.showModal();if(bridge){request('state').catch(e=>toast(e.message));poll=setInterval(()=>request('state').catch(()=>{}),1000);}else el('music-state').textContent='请在桌面客户端中打开音乐盒。';};
  el('music-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{clearInterval(poll);poll=null;});
  el('music-play').onclick=()=>run(async()=>{if(Number(el('music-volume').value)===0)await request('volume',{volume:.35});return loaded?request('play'):track();});el('music-stop').onclick=()=>run(()=>request('stop'));
  el('music-track').onchange=()=>run(track);for(const [id,delta] of [['music-prev',-1],['music-next',1]])el(id).onclick=()=>run(async()=>{el('music-track').value=(Number(el('music-track').value)+delta+tracks.length)%tracks.length;document.dispatchEvent(new Event('controlschange'));await track();});
  el('music-volume').oninput=()=>el('music-volume-value').textContent=el('music-volume').value+'%';el('music-volume').onchange=()=>run(()=>request('volume',{volume:Number(el('music-volume').value)/100}));
  el('music-import').onclick=()=>el('music-file').click();el('music-file').onchange=()=>run(async()=>{const file=el('music-file').files[0];el('music-file').value='';if(!file)return;if(file.size>8*1024*1024)throw new Error('MIDI 文件不能超过 8 MiB。');const data=new Uint8Array(await file.arrayBuffer());if(String.fromCharCode(...data.subarray(0,4))!=='MThd')throw new Error('请选择标准 MIDI 文件。');let binary='';for(let i=0;i<data.length;i+=8192)binary+=String.fromCharCode(...data.subarray(i,i+8192));await request('import',{data:btoa(binary),name:file.name});loaded=true;});
  if(!bridge)for(const control of dialog.querySelectorAll('button,input,select'))if(control.id!=='music-close')control.disabled=true;
  const started=bridge?request('volume',{volume:.35}).then(track).catch(e=>{toast('音乐暂时没响起来：'+e.message);return null;}):Promise.resolve();
  window.LUOYEMusicState=async()=>{await started;return request('state');};
  window.LUOYEMusicSmoke=async()=>{await started;const before=await request('state');await request('volume',{volume:0});const playing=await request('track',{index:0});if(!playing.playing||playing.volume!==0)throw new Error('MIDI bridge did not start muted playback');const stopped=await request('stop');if(stopped.playing)throw new Error('MIDI bridge did not stop');await request('volume',{volume:before.volume});if(before.playing)await request('play');return {playing,stopped,tracks:el('music-track').options.length};};
  return {request};
}
