export function mountPalette({getColor,setColor}) {
  const el=id=>document.getElementById(id),history={foreground:[],background:[]};let target='foreground',draft='#000000',alpha=1;
  const panel=document.createElement('section');panel.className='classic-colors';panel.setAttribute('aria-label','前景色与背景色');
  panel.innerHTML=`<h3>我的颜色</h3><div class="color-pair"><div class="color-slot"><button id="foreground-palette" aria-label="选择画笔颜色" title="画笔色"></button><span>画笔色</span></div><div class="color-slot"><button id="background-palette" aria-label="选择第二种颜色" title="第二色"></button><span>第二色</span></div><button id="swap-colors" aria-label="交换画笔色与第二色" title="交换两种颜色">⇄</button></div><div id="foreground-history" class="color-history" aria-label="最近用过的颜色"></div><div id="background-history" class="color-history" hidden></div><button id="palette-open">选颜色 · 调一调</button>`;
  document.querySelector('.classic-left').prepend(panel);
  const dialog=document.createElement('dialog');dialog.id='palette-dialog';dialog.className='classic-palette-dialog';dialog.innerHTML=`<h2>调色板</h2><div class="palette-editor"><div><canvas id="color-plane" width="256" height="192" tabindex="0" aria-label="色相与饱和度，方向键调整"></canvas><label>明度 <input id="color-value" type="range" min="0" max="100" value="100"></label></div><div><div id="color-preview"></div><label>红 <input id="color-red" type="number" min="0" max="255" aria-label="红色数值"></label><label>绿 <input id="color-green" type="number" min="0" max="255" aria-label="绿色数值"></label><label>蓝 <input id="color-blue" type="number" min="0" max="255" aria-label="蓝色数值"></label><label>不透明度 <input id="color-alpha" type="range" min="0" max="100"><output id="color-alpha-value"></output></label></div></div><div class="dialog-actions"><button id="palette-reset">恢复</button><button id="palette-cancel">取消</button><button id="palette-apply" class="primary">确定</button></div>`;
  document.body.append(dialog);
  const presets=document.createElement('div');presets.className='palette-presets';presets.setAttribute('aria-label','常用颜色');
  const colors=[['纯黑','#000000'],['纯白','#ffffff'],['苹果红','#ef5350'],['蜜桃粉','#ffaaa5'],['橘子橙','#ff9944'],['向日葵黄','#ffd95a'],['草地绿','#70b56b'],['薄荷绿','#9ed9c5'],['天空蓝','#6cb9e8'],['大海蓝','#3979bf'],['葡萄紫','#9b80c5'],['樱花粉','#ed9ac2'],['泥土棕','#987052'],['奶油白','#fff4d6'],['白色','#ffffff'],['灰色','#a6adb3'],['墨黑','#273b35']];
  const lastPreset=document.createElement('button');lastPreset.className='preset-color';lastPreset.id='last-color-preset';lastPreset.innerHTML='<i></i><span>上次颜色</span>';lastPreset.onclick=()=>{draft=getColor();fromHex(draft);preview();};presets.append(lastPreset);
  for(const [name,color] of colors){const button=document.createElement('button');button.className='preset-color';button.style.setProperty('--preset',color);button.setAttribute('aria-label',name);button.title=name;button.innerHTML='<i></i><span>'+name+'</span>';button.onclick=()=>{draft=color;fromHex(draft);preview();};presets.append(button);}
  dialog.querySelector('.palette-editor').before(presets);
  const advanced=document.createElement('details');advanced.className='color-numbers';advanced.innerHTML='<summary>精确调色 · 红绿蓝数值</summary><label>RGB 数组 <input id="color-rgb-array" inputmode="numeric" placeholder="例如 [255, 128, 0]" aria-label="RGB 数组"></label>'; const labels=['red','green','blue'].map(key=>el('color-'+key).closest('label'));labels[0].before(advanced);advanced.append(...labels);
  let hue=0,saturation=1,value=1,initial,paletteMap;

  function hsvToHex(h,s,v){const f=n=>{const k=(n+h/60)%6;return Math.round((v-v*s*Math.max(0,Math.min(k,4-k,1)))*255).toString(16).padStart(2,'0');};return '#'+f(5)+f(3)+f(1);}
  function fromHex(hex){const c=hex.slice(1).match(/../g).map(n=>parseInt(n,16)/255),max=Math.max(...c),min=Math.min(...c),d=max-min;value=max;saturation=max?d/max:0;hue=d?((max===c[0]?(c[1]-c[2])/d+(c[1]<c[2]?6:0):max===c[1]?(c[2]-c[0])/d+2:(c[0]-c[1])/d+4)*60):0;}
  function preview(){el('color-preview').style.background=draft;el('color-preview').style.opacity=alpha;['red','green','blue'].forEach((key,i)=>el('color-'+key).value=parseInt(draft.slice(1+i*2,3+i*2),16));el('color-value').value=value*100;el('color-alpha').value=alpha*100;el('color-alpha-value').textContent=Math.round(alpha*100)+'%';const ctx=el('color-plane').getContext('2d'),data=paletteMap||ctx.createImageData(256,192);if(!paletteMap)for(let y=0;y<192;y++)for(let x=0;x<256;x++){const hex=hsvToHex(x/255*360,1-y/191,1);const n=(y*256+x)*4;for(let k=0;k<3;k++)data.data[n+k]=parseInt(hex.slice(1+k*2,3+k*2),16);data.data[n+3]=255;}paletteMap=data;ctx.putImageData(data,0,0);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(hue/360*255-3,(1-saturation)*191-3,6,6);}
  function sync(){el('last-color-preset').style.setProperty('--preset',getColor());el('last-color-preset').querySelector('i').style.background=getColor();for(const key of ['foreground','background']){const current=key==='foreground'?getColor():el('background-color').value;el(key+'-palette').style.background=current;el(key+'-history').replaceChildren();if(key==='foreground'&&!history[key].length){const label=document.createElement('span');label.textContent='最近用过的颜色会留在这里';el(key+'-history').append(label);}for(const c of history[key]){const b=document.createElement('button');b.style.background=c;b.setAttribute('aria-label',(key==='foreground'?'前景':'背景')+'历史色 '+c);b.onclick=()=>commit(key,c);el(key+'-history').append(b);}}}
  function commit(key,c){const old=key==='foreground'?getColor():el('background-color').value;if(old!==c)history[key]=[old,...history[key].filter(v=>v!==old)].slice(0,3);if(key==='foreground')setColor(c);else el('background-color').value=c;sync();}
  function open(key){target=key;const textureOption=dialog.querySelector('.paint-texture-option');if(textureOption)textureOption.hidden=key!=='foreground';el('color-alpha').closest('label').hidden=key!=='foreground';dialog.querySelector('h2').textContent=key==='foreground'?'给画笔选个颜色':'选一个第二色';draft=key==='foreground'?getColor():el('background-color').value;alpha=Number(el('opacity').value)/100;initial={draft,alpha};fromHex(draft);preview();if(key==='foreground'){value=1;el('color-value').value=100;}dialog.showModal();}
  el('foreground-palette').onclick=()=>open('foreground');el('background-palette').onclick=()=>open('background');el('palette-open').onclick=()=>open('foreground');
  el('swap-colors').onclick=()=>{const f=getColor(),b=el('background-color').value;commit('foreground',b);commit('background',f);};
  el('palette-cancel').onclick=()=>dialog.close();el('palette-reset').onclick=()=>{({draft,alpha}=initial);fromHex(draft);preview();};el('palette-apply').onclick=()=>{commit(target,draft);if(target==='foreground'){el('opacity').value=alpha*100;el('opacity').dispatchEvent(new Event('input'));}dialog.close();};
  el('color-rgb-array').onchange=()=>{const m=el('color-rgb-array').value.match(/\d+/g)?.map(Number)||[];if(m.length!==3||m.some(n=>n<0||n>255))return;draft='#'+m.map(n=>n.toString(16).padStart(2,'0')).join('');fromHex(draft);preview();};
  for(const key of ['red','green','blue'])el('color-'+key).oninput=()=>{draft='#'+['red','green','blue'].map(k=>Math.max(0,Math.min(255,Math.round(Number(el('color-'+k).value)||0))).toString(16).padStart(2,'0')).join('');fromHex(draft);preview();};
  el('color-value').oninput=()=>{value=Number(el('color-value').value)/100;draft=hsvToHex(hue,saturation,value);preview();};el('color-alpha').oninput=()=>{alpha=Number(el('color-alpha').value)/100;el('color-preview').style.opacity=alpha;el('color-alpha-value').textContent=Math.round(alpha*100)+'%';};
  const plane=el('color-plane');let dragging=false;const point=e=>{const b=plane.getBoundingClientRect();hue=Math.max(0,Math.min(359.99,(e.clientX-b.left)/b.width*360));saturation=1-Math.max(0,Math.min(1,(e.clientY-b.top)/b.height));if(value===0)value=1;draft=hsvToHex(hue,saturation,value);preview();};plane.onpointerdown=e=>{dragging=true;plane.setPointerCapture(e.pointerId);point(e);};plane.onpointermove=e=>{if(dragging)point(e);};plane.onpointerup=plane.onpointercancel=()=>{dragging=false;};plane.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(value===0)value=1;hue=(hue+(e.key==='ArrowLeft'?-2:e.key==='ArrowRight'?2:0)+360)%360;saturation=Math.max(0,Math.min(1,saturation+(e.key==='ArrowUp'?.02:e.key==='ArrowDown'?-.02:0)));draft=hsvToHex(hue,saturation,value);preview();};
  document.addEventListener('palettechange',sync);el('background-color').addEventListener('input',sync);sync();return {sync,open};
}
