import { renderStyledText } from './text.js';
import { loadImage } from './engine.js';

export function mountText({engine,run,toast,getColor,setTool,getTool}) {
  const el=id=>document.getElementById(id),dialog=el('text-dialog');dialog.className='wide-dialog';let point,texture=null;
  const flags=[['bold','粗体'],['italic','斜体'],['underline','下划线'],['strike','删除线'],['antialias','柔和边缘'],['shadow','阴影'],['outline','中空'],['flipX','水平翻转'],['flipY','垂直翻转'],['gradient','渐变']];
  const glyphs=['B','I','U','S','柔','影','空','↔','↕','彩'];
  dialog.innerHTML=`<h2>把心里话写在画里</h2><div class="text-layout"><div><label for="text-content">输入／修改文字</label><textarea id="text-content" rows="3" maxlength="1000">落叶画板</textarea><label>字体 <select id="text-font" aria-label="字体"></select></label><label>字号 <input id="text-size" type="number" min="12" max="400" value="72"></label><div class="text-style-grid">${flags.map(([key,name],i)=>`<label class="text-style"><input type="checkbox" id="text-${key}" ${key==='antialias'?'checked':''}><span class="text-style-icon" >${glyphs[i]}</span>${name}</label>`).join('')}</div><label>底纹 <select id="text-fill"><option value="color">前景色／渐变色</option><option value="texture">图片纹理</option></select></label><div class="text-texture-actions"><button id="text-import-texture">输入底纹图片</button><button id="text-clear-texture">清除底纹</button><input id="text-texture-file" type="file" accept="image/png,image/jpeg,image/webp" hidden></div></div><div class="effect-preview"><span>文字预览</span><div id="text-preview"></div><output id="text-error" role="status"></output></div></div><div class="dialog-actions"><button id="text-cancel">取消</button><button id="text-add" class="primary">放进画里</button></div>`;
  const previewColumn=document.createElement('div');previewColumn.className='text-result';const previewPanel=dialog.querySelector('.effect-preview');previewPanel.before(previewColumn);previewColumn.append(previewPanel,el('text-fill').closest('label'),dialog.querySelector('.text-texture-actions'));
  const fonts=['PingFang SC','Songti SC','Kaiti SC','Heiti SC','Arial','Times New Roman','Courier New','Microsoft YaHei','SimSun','KaiTi'];
  function setFonts(values){const selected=el('text-font').value||fonts[0];el('text-font').replaceChildren();for(const font of [...new Set([...fonts,...values])]){const o=document.createElement('option');o.value=font;o.textContent=({'PingFang SC':'圆圆黑体','Songti SC':'整齐宋体','Kaiti SC':'毛笔楷体','Heiti SC':'粗粗黑体','Arial':'简单英文','Times New Roman':'经典英文','Courier New':'打字机'})[font]||font;el('text-font').append(o);}el('text-font').value=selected;}
  setFonts(window.LUOYE_NATIVE_FONTS||[]);window.LUOYESetFonts=values=>setFonts(values);
  function spec(){return {text:el('text-content').value,size:Number(el('text-size').value),font:el('text-font').value,color:getColor(),background:el('background-color').value,...Object.fromEntries(flags.map(([key])=>[key,el('text-'+key).checked]))};}
  function render(){if(el('text-fill').value==='texture'&&!texture)throw new Error('请先输入一张底纹图片。');return renderStyledText(spec(),el('text-fill').value==='texture'?texture:null);}
  function preview(){try{el('text-preview').replaceChildren(render());el('text-error').textContent='';el('text-add').disabled=false;}catch(e){el('text-error').textContent=e.message;el('text-add').disabled=true;}}
  for(const input of dialog.querySelectorAll('input,select,textarea'))input.addEventListener('input',preview);
  let returnTool='pen';
  el('text-cancel').onclick=()=>dialog.close();el('text-add').onclick=()=>run(()=>{const c=render();if(!spec().text.trim())throw new Error('请先输入文字。');engine.addLayer(spec().text.slice(0,24),c,true,{x:point.x+c.width/2,y:point.y+c.height/2,opacity:Number(el('opacity').value)/100});dialog.close();setTool(returnTool);toast('文字已放入独立图层，可继续当前操作；移动图层请使用移动工具');});
  el('text-import-texture').onclick=()=>el('text-texture-file').click();el('text-clear-texture').onclick=()=>{texture=null;el('text-fill').value='color';preview();document.dispatchEvent(new Event('controlschange'));};
  el('text-texture-file').onchange=()=>run(async()=>{const file=el('text-texture-file').files[0];el('text-texture-file').value='';if(!file)return;if(file.size>10*1024*1024)throw new Error('底纹图片需在 10 MiB 以内。');const url=URL.createObjectURL(file);try{const image=await loadImage(url);if(image.width*image.height>8388608)throw new Error('底纹超过 8 百万像素。');texture=image;el('text-fill').value='texture';preview();}finally{URL.revokeObjectURL(url);document.dispatchEvent(new Event('controlschange'));}});
  const options=document.createElement('button');options.id='text-options-open';options.dataset.option='text';options.textContent='字体与样式';options.onclick=()=>open({x:engine.width*.2,y:engine.height*.2});document.querySelector('.detail-bar').append(options);options.hidden=true;
  function open(p){point=p;returnTool=getTool?.()||'pen';preview();dialog.showModal();el('text-content').focus();}
  return {open};
}
